### ISSUE TITLE
Bavarian holidays 2020

### ISSUE THREAD

**Issue by fhaselbeck** [HazardDede/ferien-api#2]
Hi everybody,
thanks for your great work providing this library.

I found one issue regarding the bavarian holidays in 2020. The "Faschingsferien" in February are named "herbstferien" instead. So only a minor, quick fixable issue.

thanks and kind regards,
Florian

**Comment by HazardDede** [comment]
Hej @fhaselbeck,

thanks for your feedback. Unfortunately this is only a python client to consume the json rest api at [http://ferien-api.de/](http://ferien-api.de/). To address your issue you can contact the owner. To be honest some of the vacations 2020 for Hamburg are faulty as well :-(

Maybe some of the vacation periods changed due to corona and the owner is not aware of it? I cannot really tell because I have no kids at school age ;-)

So far
Dennis

**Comment by fhaselbeck** [comment]
Hi Dennis,

thanks for your quick reply. Sure, you are right. I just emailed them :-)

Kind regards,
Florian
